---

  - name: update apt
    apt: update_cache=yes

  - name: workaround to install postgresql with locale set
    shell: LANG={{ postgresql_locale  }} LC_COLLATE={{ postgresql_locale }} LC_CTYPE={{ postgresql_locale }} LC_MESSAGES={{ postgresql_locale }} LC_MONETARY={{ postgresql_locale }} LC_NUMERIC={{ postgresql_locale }} LC_TIME={{ postgresql_locale }} LC_ALL={{ postgresql_locale }}  apt-get install -y {{ item }}
    with_items: 
      - postgresql-{{postgres_version}}
      - postgresql-client-{{postgres_version}}
      - postgresql-contrib-{{postgres_version}}

  - name: install postgresql packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - libpq-dev
      - python-psycopg2
